just run codepipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,141 +14,141 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  lint:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  # lint:
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v3
 
-      # Set up Node.js
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16.x
-          cache: 'yarn'
+  #     # Set up Node.js
+  #     - name: Use Node.js 16.x
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16.x
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run linter check
-        run: yarn lint
+  #     - name: Run linter check
+  #       run: yarn lint
 
-  style:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  # style:
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v3
 
-      # Set up Node.js
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16.x
-          cache: 'yarn'
+  #     # Set up Node.js
+  #     - name: Use Node.js 16.x
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16.x
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run code style check
-        run: yarn style
+  #     - name: Run code style check
+  #       run: yarn style
 
-  setup-common-test:
-    runs-on: ubuntu-latest
-    outputs:
-      common-tests: ${{ steps['set-common-tests'].outputs['common-tests'] }}
-      set-common-test-names: ${{ steps['set-common-test-names'].outputs['common-test-names'] }}
-    steps:
-      - uses: actions/checkout@v3
-      - run: yarn --prefer-offline
-      - id: set-common-tests
-        name: Set common tests
-        run: >
-          echo "::set-output name=common-tests::$(npx jest **/common/* --listTests --json | jq -c 'map({(. | split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring): .}) | add')"
-      - id: set-common-test-names
-        name: Set common test names
-        run: echo "::set-output name=common-test-names::$(npx jest **/common/* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"
+  # setup-common-test:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     common-tests: ${{ steps['set-common-tests'].outputs['common-tests'] }}
+  #     set-common-test-names: ${{ steps['set-common-test-names'].outputs['common-test-names'] }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - run: yarn --prefer-offline
+  #     - id: set-common-tests
+  #       name: Set common tests
+  #       run: >
+  #         echo "::set-output name=common-tests::$(npx jest **/common/* --listTests --json | jq -c 'map({(. | split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring): .}) | add')"
+  #     - id: set-common-test-names
+  #       name: Set common test names
+  #       run: echo "::set-output name=common-test-names::$(npx jest **/common/* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"
 
-  common-test:
-    runs-on: ubuntu-latest
-    needs:
-      - setup-common-test
-    name: common.test.${{ matrix.common }}
-    strategy:
-      fail-fast: false
-      matrix:
-        common: ${{ fromJson(needs.setup-common-test.outputs['set-common-test-names']) }}
-    steps:
-      - uses: actions/checkout@v3
+  # common-test:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - setup-common-test
+  #   name: common.test.${{ matrix.common }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       common: ${{ fromJson(needs.setup-common-test.outputs['set-common-test-names']) }}
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16.x
-          cache: 'yarn'
+  #     - name: Use Node.js 16.x
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16.x
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run common tests
-        run: yarn coverage $(echo $COMMONS | jq -r '."${{matrix.common}}"')
-        env:
-          IASQL_ENV: test
-          COMMONS: ${{ needs.setup-common-test.outputs['common-tests'] }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
-          A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
+  #     - name: Run common tests
+  #       run: yarn coverage $(echo $COMMONS | jq -r '."${{matrix.common}}"')
+  #       env:
+  #         IASQL_ENV: test
+  #         COMMONS: ${{ needs.setup-common-test.outputs['common-tests'] }}
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
+  #         A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
 
-  readonly-test:
-    runs-on: ubuntu-latest
-    name: readonly tests
-    steps:
-      - uses: actions/checkout@v3
+  # readonly-test:
+  #   runs-on: ubuntu-latest
+  #   name: readonly tests
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16.x
-          cache: 'yarn'
+  #     - name: Use Node.js 16.x
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16.x
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run read-only tests
-        run: yarn coverage **/readonly/*
-        env:
-          IASQL_ENV: test
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_READONLY_TESTING }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_READONLY_TESTING }}
-          A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
+  #     - name: Run read-only tests
+  #       run: yarn coverage **/readonly/*
+  #       env:
+  #         IASQL_ENV: test
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_READONLY_TESTING }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_READONLY_TESTING }}
+  #         A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
 
-  upgrade-test:
-    runs-on: ubuntu-latest
-    name: iasql_upgrade test
-    steps:
-      - uses: actions/checkout@v3
+  # upgrade-test:
+  #   runs-on: ubuntu-latest
+  #   name: iasql_upgrade test
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16.x
-          cache: 'yarn'
+  #     - name: Use Node.js 16.x
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16.x
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run common tests
-        run: ./test/upgrade/run-upgrade.sh
-        env:
-          IASQL_ENV: test
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
-          A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
+  #     - name: Run common tests
+  #       run: ./test/upgrade/run-upgrade.sh
+  #       env:
+  #         IASQL_ENV: test
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
+  #         A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
 
   setup-module-test:
     runs-on: ubuntu-latest
@@ -233,76 +233,76 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Pre-clean Test Account
-        id: pre-clean-test-account
-        env:
-          IASQL_ENV: ci
-          ACCOUNT_INDEX: ${{ steps['determine-test-account'].outputs['account_index'] }}
-          ACCESS_KEY_IDS: ${{ secrets.ACCESS_KEY_IDS }}
-          SECRET_ACCESS_KEYS: ${{ secrets.SECRET_ACCESS_KEYS }}
-          PSQL_CONN: postgres://postgres:test@localhost:5432/iasql
-        run: |
-          # Establish needed secrets
-          export AWS_ACCESS_KEY_ID=$(echo "${ACCESS_KEY_IDS}" | jq -r ".[${ACCOUNT_INDEX}]")
-          export AWS_SECRET_ACCESS_KEY=$(echo "${SECRET_ACCESS_KEYS}" | jq -r ".[${ACCOUNT_INDEX}]")
+      # - name: Pre-clean Test Account
+      #   id: pre-clean-test-account
+      #   env:
+      #     IASQL_ENV: ci
+      #     ACCOUNT_INDEX: ${{ steps['determine-test-account'].outputs['account_index'] }}
+      #     ACCESS_KEY_IDS: ${{ secrets.ACCESS_KEY_IDS }}
+      #     SECRET_ACCESS_KEYS: ${{ secrets.SECRET_ACCESS_KEYS }}
+      #     PSQL_CONN: postgres://postgres:test@localhost:5432/iasql
+      #   run: |
+      #     # Establish needed secrets
+      #     export AWS_ACCESS_KEY_ID=$(echo "${ACCESS_KEY_IDS}" | jq -r ".[${ACCOUNT_INDEX}]")
+      #     export AWS_SECRET_ACCESS_KEY=$(echo "${SECRET_ACCESS_KEYS}" | jq -r ".[${ACCOUNT_INDEX}]")
 
-          # Spin up the engine and a postgres instance
-          # Temporarily export the engine port until it's only the Postgres port needed
-          docker run -p 5432:5432 -e IASQL_ENV=ci --name iasql ghcr.io/iasql/iasql-engine:$GITHUB_SHA &
-          while ! psql postgres://postgres:test@localhost:5432/iasql_metadata -b -q -c "SELECT iasql_engine_health()"; do sleep 1 && echo -n .; done;
+      #     # Spin up the engine and a postgres instance
+      #     # Temporarily export the engine port until it's only the Postgres port needed
+      #     docker run -p 5432:5432 -e IASQL_ENV=ci --name iasql ghcr.io/iasql/iasql-engine:$GITHUB_SHA &
+      #     while ! psql postgres://postgres:test@localhost:5432/iasql_metadata -b -q -c "SELECT iasql_engine_health()"; do sleep 1 && echo -n .; done;
 
-          # connect `iasql` db to aws account for `apply`
-          echo "\nCreating an iasql db..."
-          connectres=$(psql "postgres://postgres:test@localhost:5432/iasql_metadata" -t -c "SELECT json_agg(c)->0 FROM iasql_connect('iasql') as c;")
-          username=$(jq -r '.user' <<<"$connectres")
-          password=$(jq -r '.password' <<<"$connectres")
+      #     # connect `iasql` db to aws account for `apply`
+      #     echo "\nCreating an iasql db..."
+      #     connectres=$(psql "postgres://postgres:test@localhost:5432/iasql_metadata" -t -c "SELECT json_agg(c)->0 FROM iasql_connect('iasql') as c;")
+      #     username=$(jq -r '.user' <<<"$connectres")
+      #     password=$(jq -r '.password' <<<"$connectres")
 
-          # Setup Account
-          echo "\nInstalling aws_account..."
-          psql $PSQL_CONN -c "
-            select iasql_install(
-              'aws_account'
-            );
-          ";
+      #     # Setup Account
+      #     echo "\nInstalling aws_account..."
+      #     psql $PSQL_CONN -c "
+      #       select iasql_install(
+      #         'aws_account'
+      #       );
+      #     ";
 
-          echo "\nAttaching credentials..."
-          psql $PSQL_CONN -c "
-            INSERT INTO aws_credentials (access_key_id, secret_access_key)
-            VALUES ('${AWS_ACCESS_KEY_ID}', '${AWS_SECRET_ACCESS_KEY}');
-          ";
+      #     echo "\nAttaching credentials..."
+      #     psql $PSQL_CONN -c "
+      #       INSERT INTO aws_credentials (access_key_id, secret_access_key)
+      #       VALUES ('${AWS_ACCESS_KEY_ID}', '${AWS_SECRET_ACCESS_KEY}');
+      #     ";
 
-          # Start transaction
-          echo "\nStarting transaction..."
-          psql $PSQL_CONN -c "
-            select * from iasql_begin();
-          ";
+      #     # Start transaction
+      #     echo "\nStarting transaction..."
+      #     psql $PSQL_CONN -c "
+      #       select * from iasql_begin();
+      #     ";
 
-          # Start transaction
-          echo "\nSynchronizing..."
-          psql $PSQL_CONN -c "
-            SELECT * FROM iasql_commit();
-          ";
+      #     # Start transaction
+      #     echo "\nSynchronizing..."
+      #     psql $PSQL_CONN -c "
+      #       SELECT * FROM iasql_commit();
+      #     ";
 
-          echo "\nInstalling all modules in iasql db..."
-          psql $PSQL_CONN -c "
-            select iasql_install(
-              variadic array(select module_name from iasql_modules_list())
-            );
-          ";
+      #     echo "\nInstalling all modules in iasql db..."
+      #     psql $PSQL_CONN -c "
+      #       select iasql_install(
+      #         variadic array(select module_name from iasql_modules_list())
+      #       );
+      #     ";
 
-          # Start transaction
-          echo "\nStarting transaction..."
-          psql postgres://$username:$password@localhost:5432/iasql -c "select * from iasql_begin();"
+      #     # Start transaction
+      #     echo "\nStarting transaction..."
+      #     psql postgres://$username:$password@localhost:5432/iasql -c "select * from iasql_begin();"
 
-          # Delete all records
-          echo "\nDelete all records..."
-          psql "postgres://$username:$password@localhost:5432/iasql" -c "select * from delete_all_records();"
+      #     # Delete all records
+      #     echo "\nDelete all records..."
+      #     psql "postgres://$username:$password@localhost:5432/iasql" -c "select * from delete_all_records();"
 
-          echo "\nApply..."
-          psql $PSQL_CONN -c "select * from iasql_commit();" ; docker logs $(docker ps -a --filter "name=iasql" --format "{{.Names}}")
+      #     echo "\nApply..."
+      #     psql $PSQL_CONN -c "select * from iasql_commit();" ; docker logs $(docker ps -a --filter "name=iasql" --format "{{.Names}}")
 
-          # Shut down the engine
-          docker container stop iasql
+      #     # Shut down the engine
+      #     docker container stop iasql
 
       - name: Install dependencies
         run: yarn --prefer-offline
