add some debug

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,7 +6,7 @@ name: Integration Tests
 # events but only for the main branch.
 on:
   push:
-    branches: [main]
+    branches: [main, debug-typeorm-upgrade]
     paths:
       [
         '.github/workflows/tests.yml',
@@ -34,231 +34,231 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  lint:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  # lint:
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v3
 
-      # Set up Node.js
-      - name: Use Node.js LTS
-        uses: actions/setup-node@v3
-        with:
-          node-version: 'lts/*'
-          cache: 'yarn'
+  #     # Set up Node.js
+  #     - name: Use Node.js LTS
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 'lts/*'
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run linter check
-        run: yarn lint
+  #     - name: Run linter check
+  #       run: yarn lint
 
-  style:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  # style:
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v3
 
-      # Set up Node.js
-      - name: Use Node.js LTS
-        uses: actions/setup-node@v3
-        with:
-          node-version: 'lts/*'
-          cache: 'yarn'
+  #     # Set up Node.js
+  #     - name: Use Node.js LTS
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 'lts/*'
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run code style check
-        run: yarn style
+  #     - name: Run code style check
+  #       run: yarn style
 
-  setup-common-test:
-    runs-on: ubuntu-latest
-    outputs:
-      common-tests: ${{ steps['set-common-tests'].outputs['common-tests'] }}
-      set-common-test-names: ${{ steps['set-common-test-names'].outputs['common-test-names'] }}
-    steps:
-      - uses: actions/checkout@v3
-      - run: yarn --prefer-offline
-      - id: set-common-tests
-        name: Set common tests
-        run: >
-          echo "::set-output name=common-tests::$(npx jest **/common/* --listTests --json | jq -c 'map({(. | split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring): .}) | add')"
-      - id: set-common-test-names
-        name: Set common test names
-        run: echo "::set-output name=common-test-names::$(npx jest **/common/* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"
+  # setup-common-test:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     common-tests: ${{ steps['set-common-tests'].outputs['common-tests'] }}
+  #     set-common-test-names: ${{ steps['set-common-test-names'].outputs['common-test-names'] }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - run: yarn --prefer-offline
+  #     - id: set-common-tests
+  #       name: Set common tests
+  #       run: >
+  #         echo "::set-output name=common-tests::$(npx jest **/common/* --listTests --json | jq -c 'map({(. | split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring): .}) | add')"
+  #     - id: set-common-test-names
+  #       name: Set common test names
+  #       run: echo "::set-output name=common-test-names::$(npx jest **/common/* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"
 
-  common-test:
-    runs-on: ubuntu-latest
-    needs:
-      - setup-common-test
-    name: common.test.${{ matrix.common }}
-    strategy:
-      fail-fast: false
-      matrix:
-        common: ${{ fromJson(needs.setup-common-test.outputs['set-common-test-names']) }}
-    steps:
-      - uses: actions/checkout@v3
+  # common-test:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - setup-common-test
+  #   name: common.test.${{ matrix.common }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       common: ${{ fromJson(needs.setup-common-test.outputs['set-common-test-names']) }}
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Use Node.js LTS
-        uses: actions/setup-node@v3
-        with:
-          node-version: 'lts/*'
-          cache: 'yarn'
+  #     - name: Use Node.js LTS
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 'lts/*'
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run common tests
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 2
-          retry_on: error
-          timeout_minutes: 30
-          command: yarn coverage $(echo $COMMONS | jq -r '."${{matrix.common}}"')
-        env:
-          IASQL_ENV: test
-          COMMONS: ${{ needs.setup-common-test.outputs['common-tests'] }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
-          A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
+  #     - name: Run common tests
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         max_attempts: 2
+  #         retry_on: error
+  #         timeout_minutes: 30
+  #         command: yarn coverage $(echo $COMMONS | jq -r '."${{matrix.common}}"')
+  #       env:
+  #         IASQL_ENV: test
+  #         COMMONS: ${{ needs.setup-common-test.outputs['common-tests'] }}
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
+  #         A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
 
-  setup-basic-integration-test:
-    runs-on: ubuntu-latest
-    outputs:
-      basic-integration-tests: ${{ steps['set-basic-integration-tests'].outputs['basic-integration-tests'] }}
-      set-basic-integration-test-names: ${{ steps['set-basic-integration-test-names'].outputs['basic-integration-test-names'] }}
-    steps:
-      - uses: actions/checkout@v3
-      - run: yarn --prefer-offline
-      - id: set-basic-integration-tests
-        name: Set basic integration tests
-        run: >
-          echo "::set-output name=basic-integration-tests::$(npx jest **/basic_integration/* --listTests --json | jq -c 'map({(. | split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring): .}) | add')"
-      - id: set-basic-integration-test-names
-        name: Set basic integration test names
-        run: echo "::set-output name=basic-integration-test-names::$(npx jest **/basic_integration/* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"
+  # setup-basic-integration-test:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     basic-integration-tests: ${{ steps['set-basic-integration-tests'].outputs['basic-integration-tests'] }}
+  #     set-basic-integration-test-names: ${{ steps['set-basic-integration-test-names'].outputs['basic-integration-test-names'] }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - run: yarn --prefer-offline
+  #     - id: set-basic-integration-tests
+  #       name: Set basic integration tests
+  #       run: >
+  #         echo "::set-output name=basic-integration-tests::$(npx jest **/basic_integration/* --listTests --json | jq -c 'map({(. | split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring): .}) | add')"
+  #     - id: set-basic-integration-test-names
+  #       name: Set basic integration test names
+  #       run: echo "::set-output name=basic-integration-test-names::$(npx jest **/basic_integration/* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"
 
-  basic-integration-test:
-    runs-on: ubuntu-latest
-    needs:
-      - setup-basic-integration-test
-    name: basic-integration.test.${{ matrix.basic-integration }}
-    strategy:
-      fail-fast: false
-      matrix:
-        basic-integration: ${{ fromJson(needs.setup-basic-integration-test.outputs['set-basic-integration-test-names']) }}
-    steps:
-      - uses: actions/checkout@v3
+  # basic-integration-test:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - setup-basic-integration-test
+  #   name: basic-integration.test.${{ matrix.basic-integration }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       basic-integration: ${{ fromJson(needs.setup-basic-integration-test.outputs['set-basic-integration-test-names']) }}
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Use Node.js LTS
-        uses: actions/setup-node@v3
-        with:
-          node-version: 'lts/*'
-          cache: 'yarn'
+  #     - name: Use Node.js LTS
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 'lts/*'
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Determine Test Account To Use
-        id: determine-test-account
-        env:
-          SECRET_HEADER: ${{ secrets.SECRET_HEADER }}
-          LAMBDA_FUNCTION: 'https://22quullhnmsrttacexxc74uium0nndzo.lambda-url.us-east-2.on.aws/'
-        run: |
-          RESPONSE=$(curl -X POST -H "Content-Type: text/plain" -H "${SECRET_HEADER}" -d '1' ${LAMBDA_FUNCTION} 2>/dev/null)
-          echo $RESPONSE
-          ACCOUNT_INDEX=$(echo $RESPONSE | jq '.[0]' || exit 1)
-          echo "::set-output name=account_index::$(echo ${ACCOUNT_INDEX})"
+  #     - name: Determine Test Account To Use
+  #       id: determine-test-account
+  #       env:
+  #         SECRET_HEADER: ${{ secrets.SECRET_HEADER }}
+  #         LAMBDA_FUNCTION: 'https://22quullhnmsrttacexxc74uium0nndzo.lambda-url.us-east-2.on.aws/'
+  #       run: |
+  #         RESPONSE=$(curl -X POST -H "Content-Type: text/plain" -H "${SECRET_HEADER}" -d '1' ${LAMBDA_FUNCTION} 2>/dev/null)
+  #         echo $RESPONSE
+  #         ACCOUNT_INDEX=$(echo $RESPONSE | jq '.[0]' || exit 1)
+  #         echo "::set-output name=account_index::$(echo ${ACCOUNT_INDEX})"
 
-      - name: Run basic-integration tests
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 2
-          retry_on: error
-          timeout_minutes: 10
-          command: |
-            export AWS_ACCESS_KEY_ID=$(echo "${ACCESS_KEY_IDS}" | jq -r ".[${ACCOUNT_INDEX}]")
-            export AWS_SECRET_ACCESS_KEY=$(echo "${SECRET_ACCESS_KEYS}" | jq -r ".[${ACCOUNT_INDEX}]")
-            yarn coverage $(echo $TESTS | jq -r '."${{matrix.basic-integration}}"')
-        env:
-          IASQL_ENV: test
-          TESTS: ${{ needs.setup-basic-integration-test.outputs['basic-integration-tests'] }}
-          ACCOUNT_INDEX: ${{ steps['determine-test-account'].outputs['account_index'] }}
-          ACCESS_KEY_IDS: ${{ secrets.ACCESS_KEY_IDS }}
-          SECRET_ACCESS_KEYS: ${{ secrets.SECRET_ACCESS_KEYS }}
-          A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
+  #     - name: Run basic-integration tests
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         max_attempts: 2
+  #         retry_on: error
+  #         timeout_minutes: 10
+  #         command: |
+  #           export AWS_ACCESS_KEY_ID=$(echo "${ACCESS_KEY_IDS}" | jq -r ".[${ACCOUNT_INDEX}]")
+  #           export AWS_SECRET_ACCESS_KEY=$(echo "${SECRET_ACCESS_KEYS}" | jq -r ".[${ACCOUNT_INDEX}]")
+  #           yarn coverage $(echo $TESTS | jq -r '."${{matrix.basic-integration}}"')
+  #       env:
+  #         IASQL_ENV: test
+  #         TESTS: ${{ needs.setup-basic-integration-test.outputs['basic-integration-tests'] }}
+  #         ACCOUNT_INDEX: ${{ steps['determine-test-account'].outputs['account_index'] }}
+  #         ACCESS_KEY_IDS: ${{ secrets.ACCESS_KEY_IDS }}
+  #         SECRET_ACCESS_KEYS: ${{ secrets.SECRET_ACCESS_KEYS }}
+  #         A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
 
-      - name: Return test account
-        if: always()
-        env:
-          SECRET_HEADER: ${{ secrets.SECRET_HEADER }}
-          ACCOUNT_INDEX: ${{ steps['determine-test-account'].outputs['account_index'] }}
-          LAMBDA_FUNCTION: 'https://22quullhnmsrttacexxc74uium0nndzo.lambda-url.us-east-2.on.aws/'
-        run: |
-          curl -X POST -H "Content-Type: application/json" -H "${SECRET_HEADER}" -H "x-iasql-drop: true" -d "[${ACCOUNT_INDEX}]" ${LAMBDA_FUNCTION}
+  #     - name: Return test account
+  #       if: always()
+  #       env:
+  #         SECRET_HEADER: ${{ secrets.SECRET_HEADER }}
+  #         ACCOUNT_INDEX: ${{ steps['determine-test-account'].outputs['account_index'] }}
+  #         LAMBDA_FUNCTION: 'https://22quullhnmsrttacexxc74uium0nndzo.lambda-url.us-east-2.on.aws/'
+  #       run: |
+  #         curl -X POST -H "Content-Type: application/json" -H "${SECRET_HEADER}" -H "x-iasql-drop: true" -d "[${ACCOUNT_INDEX}]" ${LAMBDA_FUNCTION}
 
-  readonly-test:
-    runs-on: ubuntu-latest
-    name: readonly tests
-    steps:
-      - uses: actions/checkout@v3
+  # readonly-test:
+  #   runs-on: ubuntu-latest
+  #   name: readonly tests
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Use Node.js LTS
-        uses: actions/setup-node@v3
-        with:
-          node-version: 'lts/*'
-          cache: 'yarn'
+  #     - name: Use Node.js LTS
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 'lts/*'
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run read-only tests
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 2
-          retry_on: error
-          timeout_minutes: 40
-          command: yarn coverage **/readonly/*
-        env:
-          IASQL_ENV: test
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_READONLY_TESTING }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_READONLY_TESTING }}
-          A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
+  #     - name: Run read-only tests
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         max_attempts: 2
+  #         retry_on: error
+  #         timeout_minutes: 40
+  #         command: yarn coverage **/readonly/*
+  #       env:
+  #         IASQL_ENV: test
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_READONLY_TESTING }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_READONLY_TESTING }}
+  #         A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
 
-  upgrade-test:
-    runs-on: ubuntu-latest
-    name: iasql_upgrade test
-    steps:
-      - uses: actions/checkout@v3
+  # upgrade-test:
+  #   runs-on: ubuntu-latest
+  #   name: iasql_upgrade test
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Use Node.js LTS
-        uses: actions/setup-node@v3
-        with:
-          node-version: 'lts/*'
-          cache: 'yarn'
+  #     - name: Use Node.js LTS
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 'lts/*'
+  #         cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn --prefer-offline
+  #     - name: Install dependencies
+  #       run: yarn --prefer-offline
 
-      - name: Run common tests
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 2
-          timeout_minutes: 30
-          retry_on: error
-          command: ./test/upgrade/run-upgrade.sh
-        env:
-          IASQL_ENV: test
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
-          A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
+  #     - name: Run common tests
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         max_attempts: 2
+  #         timeout_minutes: 30
+  #         retry_on: error
+  #         command: ./test/upgrade/run-upgrade.sh
+  #       env:
+  #         IASQL_ENV: test
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
+  #         A0_IASQL_API_TOKEN: ${{ secrets.A0_IASQL_API_TOKEN }}
 
   setup-module-test:
     runs-on: ubuntu-latest
@@ -272,10 +272,10 @@ jobs:
       - id: set-test-modules
         name: Set modules tests
         run: >
-          echo "::set-output name=test-modules::$(npx jest **/modules/* --listTests --json | jq -c 'map({(. | split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring): .}) | add')"
+          echo "::set-output name=test-modules::$(npx jest **/modules/*ecs-integration* --listTests --json | jq -c 'map({(. | split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring): .}) | add')"
       - id: set-test-module-names
         name: Set modules tests names
-        run: echo "::set-output name=test-module-names::$(npx jest **/modules/* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"
+        run: echo "::set-output name=test-module-names::$(npx jest **/modules/*ecs-integration* --listTests --json | jq -c 'map(split("/") | .[-1] | split(".") | .[0] | gsub( "-"; "_") | ascii_upcase | tostring)')"
       - id: set-registry-image-tag
         name: Set registry image tag
         run: echo "::set-output name=registry-image-tag::ghcr.io/iasql/iasql:$GITHUB_SHA"
